name=mailshield_user
service=cpanel
url=/frontend/jupiter/mailshield/index.live.php
user=cpanel
acls=any
displayname=GokyuzuWebSpam Mail
entryurl=mailshield/index.live.php
icon=mailshield/icon.png
target=_self
feature=mailshield_user
group_id=email
