# WHM AppConfig for MailShield Pro
#
# Registered via:  /usr/local/cpanel/bin/register_appconfig /var/cpanel/apps/mailshield.conf
#
name=mailshield
service=whostmgr
url=/cgi/mailshield/index.cgi
displayname=MailShield Pro
target=_self
entryurl=cgi/mailshield/index.cgi
icon=/cgi/mailshield/icon.png
acl=any
feature=mailshield
