name=mailshield_user
service=cpanel
url=/3rdparty/mailshield/index.live.php
user=cpanel
acls=any
displayname=GokyuzuWebSpam Mail
entryurl=3rdparty/mailshield/index.live.php
icon=mailshield/icon.png
target=_self
feature=mailshield_user
group_id=email
