# WHM AppConfig for GökyüzüWebSpam
#
# Registered via:  /usr/local/cpanel/bin/register_appconfig /var/cpanel/apps/mailshield.conf
#
name=mailshield
service=whostmgr
url=/cgi/mailshield/index.cgi
displayname=GökyüzüWebSpam
target=_self
entryurl=cgi/mailshield/index.cgi
icon=/cgi/mailshield/icon.png
acl=basic-whm-functions
feature=mailshield
